version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:16.17.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            - v1-npm-deps-
      - run:
          name: Install Node.js dependencies
          command: |
            npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
      - run:
          name: Build the App
          command: |
            npm run build
      - run:
          name: Verify build folder exists
          command: |
            ls -al build/
      - persist_to_workspace:
          root: ~/
          paths:
            - project/build

  test:
    docker:
      - image: cimg/node:16.17.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            - v1-npm-deps-
      - run:
          name: Install Node.js dependencies
          command: |
            npm install
      - run:
          name: Run Unit Tests
          command: |
            npm test -- --watchAll=false

  analyze:
    docker:
      - image: cimg/node:16.17.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            - v1-npm-deps-
      - run:
          name: Install Node.js dependencies
          command: |
            npm install
      - run:
          name: Analyze source code for critical vulnerabilities
          command: |
            npm audit --audit-level=critical

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Install AWS CLI
          command: |
            sudo apt update && sudo apt install unzip curl -y

            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
      - attach_workspace:
          at: ~/
      - run:
          name: Sync build folder to the S3 bucket
          command: |
            aws s3 sync ~/project/build/ s3://$S3_BUCKET_NAME/

  verify:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Install curl
          command: |
            sudo apt update && sudo apt install curl -y
      - run:
          name: Verify website works
          command: |
            if curl -s http://$S3_BUCKET_NAME.s3-website-$AWS_DEFAULT_REGION.amazonaws.com | grep "React App"
            then
              echo "Website works fine!"
              exit 0
            else
              echo "Website doesn't work fine"
              exit 1
            fi

workflows:
  default:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - build
      - deploy:
          requires:
            - test
            - analyze
      - verify:
          requires:
            - deploy
